### ISSUE TITLE
arm - error in mmap (Errno::EINVAL)

### ISSUE THREAD

**Issue by JustDevZero** [AsydSolutions/ASYD#84]
Trying to run ASYD on my cubietruck fails.

Input:
asyd@cubietruck:~/asyd-files$ sh asyd.sh start
master failed to start, check stderr log for details
ASYD Started

Aditional info:
Linux cubietruck 3.4.107-cubietruck #14 SMP PREEMPT Wed Apr 29 11:57:42 CEST 2015 armv7l GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:        testing
Codename:       stretch

Output:
asyd@cubietruck:~/asyd-files$ sh asyd.sh start
  INFO -- : Refreshing Gem list
/home/asyd/.gem/gems/process_shared-0.2.0/lib/process_shared/posix/errno.rb:28:in `block (2 levels) in error_check': Invalid argument - error in mmap (Errno::EINVAL)
        from /home/asyd/.gem/gems/process_shared-0.2.0/lib/process_shared/posix/shared_memory.rb:62:in `initialize'
        from /home/asyd/asyd-files/models/monitor.rb:4:in `new'
        from /home/asyd/asyd-files/models/monitor.rb:4:in `<module:Monitoring>'
        from /home/asyd/asyd-files/models/monitor.rb:1:in `<top (required)>'
        from /home/asyd/asyd-files/models/init.rb:32:in `require_relative'
        from /home/asyd/asyd-files/models/init.rb:32:in `<top (required)>'
        from main.rb:3:in `require_relative'
        from main.rb:3:in `<top (required)>'
        from config.ru:13:in `load'
        from config.ru:13:in `block in <main>'
        from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /usr/lib/ruby/vendor_ruby/unicorn.rb:48:in `eval'
        from /usr/lib/ruby/vendor_ruby/unicorn.rb:48:in `block in builder'
        from /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:764:in `call'
        from /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:764:in `build_app!'
        from /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:137:in `start'
        from /usr/bin/unicorn:126:in `<main>'

**Comment by Choms** [comment]
This looks like an issue with ProcessShared, we have to take in mind that this gem relies on some POSIX specific C functions that may be different on ARM architecture (or whatever other reason, I would need to see the internals of the gem to see exactly what's the problem).

ASYD is developed and tested to run on x86/x64 architectures, I could check on this issue but sadly for now is not a priority.

However, if you (or someone else) wants to check this issue to make ASYD to work on ARM I'll be happy to accept a pull-request. The relevant part to address the issue is:

Invalid argument - error in mmap (Errno::EINVAL) from /home/asyd/.gem/gems/process_shared-0.2.0/lib/process_shared/posix/shared_memory.rb:62

**Comment by JustDevZero** [comment]
I just filled an issue on the original project https://github.com/pmahoney/process_shared/issues/13

But the developer looks a bit... unactive :(
